[package]
name = "extract-wish-url"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
bstr = "1.10.0"
enum-assoc = "1.1.0"
strum = "0.26.3"
strum_macros = "0.26.4"
tempfile = "3.13.0"
